env:
  es6: true
  node: true
  es2020: true

plugins:
  - haraka
  - prettier

root: true

rules:
  semi-style: [ error, last ]
  prefer-template: "warn"
  no-unneeded-ternary: 1


extends: ["eslint:recommended", "plugin:haraka/recommended", "plugin:prettier/recommended"]

globals:
  server: true
  OK: true
  CONT: true
  DENY: true
  DENYSOFT: true
  DENYDISCONNECT: true
  DENYSOFTDISCONNECT: true
  NEXT_HOOK: true
